/**
 * G.A.N.E — System Architecture Data
 * ======================================
 * All 2,246 Rust crates from the Devin project (Phase 0), categorized into 20 system layers.
 * Extracted from Trade-devin-1773587117-gane-nav-phase0.zip
 * Total: 2,246 crates built, 4,600+ tests passing.
 * Full G.A.N.E specification: 200 sections, 24 layer categories, 1,359+ features.
 */

export interface Crate {
  name: string;
  description: string;
  tests: number;
  status: 'active' | 'building' | 'planned';
}

export interface SystemLayer {
  id: string;
  name: string;
  nameHe: string;
  icon: string;
  color: string;
  description: string;
  descriptionHe: string;
  crates: Crate[];
}

export const systemStats = {
  totalCrates: 2246,
  totalTests: 4600,
  totalLinesOfCode: 1200000,
  languages: ['Rust', 'TypeScript', 'Python', 'GLSL', 'C++', 'WebAssembly'],
  buildPhases: 2246,
  pullRequests: 81,
  totalSpecSections: 200,
  totalSpecFeatures: 1359,
  specLayerCategories: 24,
};

export const systemLayers: SystemLayer[] = [
  {
    id: 'core-engine',
    name: 'Core Engine',
    nameHe: 'מנוע ליבה',
    icon: '⚡',
    color: 'oklch(0.82 0.15 192)',
    description: 'Foundational runtime — event bus, state machines, configuration, error handling, SDK, and subsystem synchronization.',
    descriptionHe: 'זמן ריצה בסיסי — אפיק אירועים, מכונות מצב, תצורה, טיפול בשגיאות, SDK וסנכרון תת-מערכות.',
    crates: [
      { name: 'gane-core', description: 'Central runtime kernel and lifecycle manager', tests: 45, status: 'active' },
      { name: 'gane-events', description: 'Event-driven architecture bus with pub/sub', tests: 38, status: 'active' },
      { name: 'gane-config', description: 'Hierarchical configuration with hot-reload', tests: 32, status: 'active' },
      { name: 'gane-errors', description: 'Structured error types and propagation', tests: 28, status: 'active' },
      { name: 'gane-fsm', description: 'Finite state machine framework', tests: 35, status: 'active' },
      { name: 'gane-clock', description: 'High-precision timing and synchronization', tests: 22, status: 'active' },
      { name: 'gane-sdk', description: 'Public SDK for third-party integrations', tests: 40, status: 'active' },
      { name: 'gane-api', description: 'REST/gRPC API gateway layer (Axum)', tests: 48, status: 'active' },
      { name: 'gane-app', description: 'Application bootstrap and DI container', tests: 30, status: 'active' },
      { name: 'gane-web', description: 'Web interface and dashboard server', tests: 42, status: 'active' },
      { name: 'gane-developer', description: 'Developer tools and debugging', tests: 20, status: 'active' },
      { name: 'gane-marketplace', description: 'Plugin marketplace integration', tests: 25, status: 'active' },
      { name: 'gane-plugins', description: 'Plugin system and extension framework', tests: 18, status: 'active' },
      { name: 'gane-gateway', description: 'API gateway and request routing', tests: 35, status: 'active' },
      { name: 'gane-grpc', description: 'gRPC service definitions', tests: 22, status: 'active' },
      { name: 'gane-graphql', description: 'GraphQL schema and resolvers', tests: 28, status: 'active' },
      { name: 'gane-websocket', description: 'WebSocket real-time communication', tests: 30, status: 'active' },
      { name: 'gane-weblink', description: 'Deep linking and URL routing', tests: 15, status: 'active' },
    ],
  },
  {
    id: 'positioning',
    name: 'Positioning & GNSS',
    nameHe: 'מיקום ו-GNSS',
    icon: '📡',
    color: 'oklch(0.75 0.18 150)',
    description: 'Multi-GNSS positioning (GPS/Galileo/GLONASS/BeiDou/QZSS), RTK corrections, integrity monitoring, dead reckoning.',
    descriptionHe: 'מיקום רב-GNSS, תיקוני RTK, ניטור שלמות, ניווט אינרציאלי.',
    crates: [
      { name: 'gane-gnss', description: 'Multi-constellation GNSS receiver', tests: 52, status: 'active' },
      { name: 'gane-multi-gnss', description: 'Multi-GNSS constellation manager', tests: 35, status: 'active' },
      { name: 'gane-agnss', description: 'Assisted GNSS for faster fixes', tests: 20, status: 'active' },
      { name: 'gane-corrections', description: 'RTK/PPP centimeter corrections', tests: 38, status: 'active' },
      { name: 'gane-sensors', description: 'IMU, barometer, odometry abstraction', tests: 42, status: 'active' },
      { name: 'gane-fusion', description: 'Extended Kalman Filter sensor fusion', tests: 48, status: 'active' },
      { name: 'gane-ekf', description: 'EKF implementation for position estimation', tests: 30, status: 'active' },
      { name: 'gane-integrity', description: 'RAIM, protection levels, jamming detection', tests: 45, status: 'active' },
      { name: 'gane-continuity', description: 'Continuous positioning guarantee', tests: 28, status: 'active' },
      { name: 'gane-dead-reckoning', description: 'Inertial navigation for GNSS-denied', tests: 32, status: 'active' },
      { name: 'gane-indoor', description: 'BLE beacon trilateration, WiFi RTT', tests: 25, status: 'active' },
      { name: 'gane-accel-sensor', description: 'Accelerometer sensor processing', tests: 15, status: 'active' },
      { name: 'gane-gyro', description: 'Gyroscope data processing', tests: 18, status: 'active' },
      { name: 'gane-baro', description: 'Barometric altitude estimation', tests: 12, status: 'active' },
      { name: 'gane-gps', description: 'GPS-specific receiver module', tests: 20, status: 'active' },
      { name: 'gane-satellite', description: 'Satellite orbit prediction', tests: 22, status: 'active' },
      { name: 'gane-elevation', description: 'Elevation model and terrain data', tests: 16, status: 'active' },
      { name: 'gane-geofence', description: 'Geofencing engine', tests: 24, status: 'active' },
      { name: 'gane-geocoder', description: 'Address geocoding and reverse geocoding', tests: 28, status: 'active' },
      { name: 'gane-location', description: 'Location services abstraction', tests: 20, status: 'active' },
    ],
  },
  {
    id: 'navigation',
    name: 'Navigation & Routing',
    nameHe: 'ניווט וניתוב',
    icon: '🧭',
    color: 'oklch(0.55 0.22 264)',
    description: 'A*/Dijkstra routing, lane guidance, micro-navigation, multi-stop optimization, risk-aware routing.',
    descriptionHe: 'ניתוב A*/Dijkstra, הנחיית נתיבים, מיקרו-ניווט, אופטימיזציה רב-עצירות.',
    crates: [
      { name: 'gane-routing', description: 'A* and Dijkstra route planning', tests: 55, status: 'active' },
      { name: 'gane-lane', description: 'Lane-level guidance and turn-by-turn', tests: 40, status: 'active' },
      { name: 'gane-micro-nav', description: 'Micro-navigation for last 100m', tests: 18, status: 'active' },
      { name: 'gane-multistop', description: 'Multi-stop route optimization', tests: 22, status: 'active' },
      { name: 'gane-risk', description: 'Probabilistic route risk scoring', tests: 35, status: 'active' },
      { name: 'gane-confidence', description: 'Route confidence intervals', tests: 28, status: 'active' },
      { name: 'gane-probabilistic', description: 'Probabilistic routing engine', tests: 30, status: 'active' },
      { name: 'gane-eta', description: 'ML-enhanced ETA prediction', tests: 25, status: 'active' },
      { name: 'gane-isochrone', description: 'Isochrone map generation', tests: 18, status: 'active' },
      { name: 'gane-offline', description: 'Offline map tiles and routing', tests: 32, status: 'active' },
      { name: 'gane-weather-route', description: 'Weather-aware route planning', tests: 20, status: 'active' },
      { name: 'gane-weather-nav', description: 'Weather navigation integration', tests: 15, status: 'active' },
      { name: 'gane-highway', description: 'Highway-specific routing logic', tests: 12, status: 'active' },
      { name: 'gane-intersection', description: 'Intersection modeling and timing', tests: 22, status: 'active' },
      { name: 'gane-corner', description: 'Corner detection and speed advisory', tests: 14, status: 'active' },
    ],
  },
  {
    id: 'maps-viz',
    name: 'Maps & Visualization',
    nameHe: 'מפות והדמיה',
    icon: '🗺️',
    color: 'oklch(0.72 0.14 180)',
    description: 'Map rendering, tile management, AR navigation overlay, 3D visualization, immersive display.',
    descriptionHe: 'רינדור מפות, ניהול אריחים, שכבת AR, הדמיה תלת-ממדית.',
    crates: [
      { name: 'gane-map', description: 'Map data management and matching', tests: 45, status: 'active' },
      { name: 'gane-tiles', description: 'Vector/raster tile rendering', tests: 30, status: 'active' },
      { name: 'gane-ar-nav', description: 'AR waypoint overlay with pinhole camera', tests: 35, status: 'active' },
      { name: 'gane-ar', description: 'Augmented Reality core engine', tests: 28, status: 'active' },
      { name: 'gane-immersive', description: 'Immersive VR/AR navigation', tests: 22, status: 'active' },
      { name: 'gane-visual-hierarchy', description: 'Visual hierarchy rendering', tests: 15, status: 'active' },
      { name: 'gane-visual-density', description: 'Adaptive visual density', tests: 12, status: 'active' },
      { name: 'gane-visual-dynamic', description: 'Dynamic visual effects', tests: 18, status: 'active' },
      { name: 'gane-visual-lang', description: 'Visual language system', tests: 10, status: 'active' },
      { name: 'gane-marker', description: 'Map marker management', tests: 20, status: 'active' },
      { name: 'gane-vision-slam', description: 'Visual SLAM for AR positioning', tests: 25, status: 'active' },
      { name: 'gane-vision-depth', description: 'Depth estimation from camera', tests: 18, status: 'active' },
      { name: 'gane-vision-detect', description: 'Object detection pipeline', tests: 22, status: 'active' },
      { name: 'gane-vision-segment', description: 'Semantic segmentation', tests: 20, status: 'active' },
      { name: 'gane-vision-flow', description: 'Optical flow estimation', tests: 15, status: 'active' },
      { name: 'gane-vision-calib', description: 'Camera calibration', tests: 12, status: 'active' },
    ],
  },
  {
    id: 'vehicle-v2x',
    name: 'Vehicle & V2X',
    nameHe: 'רכב ו-V2X',
    icon: '🚗',
    color: 'oklch(0.80 0.16 75)',
    description: 'Vehicle-to-Everything communication (DSRC/C-V2X), BSM, SPaT, GLOSA, vehicle diagnostics, OBD-II.',
    descriptionHe: 'תקשורת רכב-לכל (DSRC/C-V2X), BSM, SPaT, GLOSA, אבחון רכב.',
    crates: [
      { name: 'gane-v2x', description: 'V2X communication (DSRC/C-V2X)', tests: 40, status: 'active' },
      { name: 'gane-vehicle', description: 'Vehicle state and telemetry', tests: 35, status: 'active' },
      { name: 'gane-dsrc', description: 'DSRC 802.11p communication', tests: 22, status: 'active' },
      { name: 'gane-bsm', description: 'Basic Safety Message protocol', tests: 18, status: 'active' },
      { name: 'gane-vin-decode', description: 'VIN decoder for vehicle info', tests: 15, status: 'active' },
      { name: 'gane-diagnostics', description: 'OBD-II diagnostic interface', tests: 28, status: 'active' },
      { name: 'gane-dtc', description: 'Diagnostic trouble code reader', tests: 12, status: 'active' },
      { name: 'gane-ecu', description: 'ECU communication interface', tests: 20, status: 'active' },
      { name: 'gane-abs-ctrl', description: 'ABS control monitoring', tests: 15, status: 'active' },
      { name: 'gane-adaptive-cruise', description: 'Adaptive cruise control', tests: 22, status: 'active' },
      { name: 'gane-aeb-sys', description: 'Automatic emergency braking', tests: 18, status: 'active' },
      { name: 'gane-lka', description: 'Lane keep assist', tests: 16, status: 'active' },
      { name: 'gane-ldw', description: 'Lane departure warning', tests: 14, status: 'active' },
      { name: 'gane-bluetooth', description: 'Bluetooth vehicle pairing', tests: 12, status: 'active' },
      { name: 'gane-nfc', description: 'NFC key and payment', tests: 10, status: 'active' },
      { name: 'gane-5g-modem', description: '5G modem integration', tests: 18, status: 'active' },
      { name: 'gane-wifi-modem', description: 'WiFi connectivity module', tests: 12, status: 'active' },
    ],
  },
  {
    id: 'traffic',
    name: 'Traffic Intelligence',
    nameHe: 'מודיעין תנועה',
    icon: '🚦',
    color: 'oklch(0.65 0.22 25)',
    description: 'Real-time traffic flow, congestion prediction, demand forecasting, herd suppression, stability control.',
    descriptionHe: 'זרימת תנועה בזמן אמת, חיזוי עומסים, תחזית ביקוש, דיכוי עדר.',
    crates: [
      { name: 'gane-traffic', description: 'Traffic flow control and monitoring', tests: 36, status: 'active' },
      { name: 'gane-stability', description: 'Traffic stability and herd suppression', tests: 34, status: 'active' },
      { name: 'gane-crowd-speed', description: 'Crowd-sourced speed data', tests: 20, status: 'active' },
      { name: 'gane-speed-limit', description: 'Speed limit detection', tests: 15, status: 'active' },
      { name: 'gane-speed-zone', description: 'Speed zone management', tests: 12, status: 'active' },
      { name: 'gane-incident', description: 'Incident detection engine', tests: 25, status: 'active' },
      { name: 'gane-incidents', description: 'Incident management system', tests: 22, status: 'active' },
      { name: 'gane-accident-alert', description: 'Accident alert system', tests: 18, status: 'active' },
      { name: 'gane-forecast', description: 'Traffic demand forecasting', tests: 28, status: 'active' },
      { name: 'gane-construction', description: 'Construction zone detection', tests: 14, status: 'active' },
      { name: 'gane-hazmat', description: 'Hazardous material routing', tests: 16, status: 'active' },
    ],
  },
  {
    id: 'safety',
    name: 'Safety & Trust',
    nameHe: 'בטיחות ואמון',
    icon: '🛡️',
    color: 'oklch(0.75 0.18 150)',
    description: 'Anti-manipulation, evidence chain, trust scoring, collision avoidance, fatigue detection.',
    descriptionHe: 'אנטי-מניפולציה, שרשרת ראיות, ציון אמון, מניעת התנגשות.',
    crates: [
      { name: 'gane-anti-manipulation', description: 'Anti-spoofing and manipulation detection', tests: 30, status: 'active' },
      { name: 'gane-evidence', description: 'Evidence chain and trust scoring', tests: 28, status: 'active' },
      { name: 'gane-trust', description: 'Trust metrics and reputation', tests: 25, status: 'active' },
      { name: 'gane-collision', description: 'Collision detection and avoidance', tests: 22, status: 'active' },
      { name: 'gane-fatigue', description: 'Driver fatigue detection', tests: 18, status: 'active' },
      { name: 'gane-dms', description: 'Driver monitoring system', tests: 20, status: 'active' },
      { name: 'gane-evasive', description: 'Evasive maneuver planning', tests: 15, status: 'active' },
      { name: 'gane-bsw', description: 'Blind spot warning', tests: 12, status: 'active' },
      { name: 'gane-child', description: 'Child safety lock system', tests: 10, status: 'active' },
      { name: 'gane-fire', description: 'Fire detection system', tests: 14, status: 'active' },
      { name: 'gane-airbag-ctrl', description: 'Airbag control interface', tests: 16, status: 'active' },
      { name: 'gane-airbag-diag', description: 'Airbag diagnostics', tests: 12, status: 'active' },
      { name: 'gane-alarm-sys', description: 'Vehicle alarm system', tests: 10, status: 'active' },
    ],
  },
  {
    id: 'ai-ml',
    name: 'AI & Machine Learning',
    nameHe: 'בינה מלאכותית',
    icon: '🧠',
    color: 'oklch(0.60 0.25 300)',
    description: 'ML models, neural networks, prediction engines, NLP, computer vision, autonomous driving.',
    descriptionHe: 'מודלי למידת מכונה, רשתות נוירונים, מנועי חיזוי, NLP, ראייה ממוחשבת.',
    crates: [
      { name: 'gane-ml', description: 'Machine learning framework', tests: 35, status: 'active' },
      { name: 'gane-automl', description: 'Automated ML pipeline', tests: 20, status: 'active' },
      { name: 'gane-cnn', description: 'Convolutional neural networks', tests: 18, status: 'active' },
      { name: 'gane-attention', description: 'Attention mechanism for transformers', tests: 15, status: 'active' },
      { name: 'gane-nlp', description: 'Natural language processing', tests: 22, status: 'active' },
      { name: 'gane-neural', description: 'Neural network inference engine', tests: 25, status: 'active' },
      { name: 'gane-gan', description: 'Generative adversarial networks', tests: 12, status: 'active' },
      { name: 'gane-deep', description: 'Deep learning framework', tests: 28, status: 'active' },
      { name: 'gane-autonomous', description: 'Autonomous driving stack', tests: 30, status: 'active' },
      { name: 'gane-simulation', description: 'Driving simulation engine', tests: 22, status: 'active' },
      { name: 'gane-decision', description: 'Decision-making engine', tests: 18, status: 'active' },
      { name: 'gane-intent', description: 'User intent prediction', tests: 20, status: 'active' },
      { name: 'gane-gamification', description: 'Gamification engine', tests: 15, status: 'active' },
      { name: 'gane-ab-test', description: 'A/B testing framework', tests: 12, status: 'active' },
    ],
  },
  {
    id: 'fleet-ops',
    name: 'Fleet & Emergency',
    nameHe: 'צי וחירום',
    icon: '🚛',
    color: 'oklch(0.65 0.22 25)',
    description: 'Fleet management, emergency routing, ambulance/police dispatch, resource allocation.',
    descriptionHe: 'ניהול צי, ניתוב חירום, שיגור אמבולנסים/משטרה, הקצאת משאבים.',
    crates: [
      { name: 'gane-fleet', description: 'Fleet management and tracking', tests: 35, status: 'active' },
      { name: 'gane-emergency', description: 'Emergency routing and dispatch', tests: 30, status: 'active' },
      { name: 'gane-emergency-sat', description: 'Emergency satellite communication', tests: 18, status: 'active' },
      { name: 'gane-emer', description: 'Emergency services integration', tests: 15, status: 'active' },
      { name: 'gane-city', description: 'Smart city integration', tests: 25, status: 'active' },
      { name: 'gane-twin', description: 'Digital twin simulation', tests: 28, status: 'active' },
      { name: 'gane-parking', description: 'Smart parking management', tests: 22, status: 'active' },
      { name: 'gane-charging', description: 'EV charging station management', tests: 20, status: 'active' },
      { name: 'gane-autopark', description: 'Automated parking system', tests: 16, status: 'active' },
      { name: 'gane-resilience', description: 'System resilience and failover', tests: 25, status: 'active' },
      { name: 'gane-edge', description: 'Edge computing for vehicles', tests: 18, status: 'active' },
    ],
  },
  {
    id: 'payments',
    name: 'Payments & Economy',
    nameHe: 'תשלומים וכלכלה',
    icon: '💳',
    color: 'oklch(0.80 0.16 75)',
    description: 'Payment processing, toll management, wallet, blockchain, marketplace transactions.',
    descriptionHe: 'עיבוד תשלומים, ניהול אגרות, ארנק, בלוקצ\'יין, עסקאות.',
    crates: [
      { name: 'gane-payments', description: 'Payment processing engine', tests: 30, status: 'active' },
      { name: 'gane-blockchain', description: 'Blockchain ledger integration', tests: 22, status: 'active' },
      { name: 'gane-economics', description: 'Economic modeling engine', tests: 18, status: 'active' },
      { name: 'gane-cost', description: 'Cost optimization engine', tests: 15, status: 'active' },
      { name: 'gane-lease', description: 'Vehicle leasing management', tests: 12, status: 'active' },
      { name: 'gane-investor', description: 'Investment analytics', tests: 10, status: 'active' },
      { name: 'gane-warranty-mgr', description: 'Warranty management', tests: 14, status: 'active' },
    ],
  },
  {
    id: 'voice-ux',
    name: 'Voice & UX',
    nameHe: 'קול וחוויית משתמש',
    icon: '🎙️',
    color: 'oklch(0.72 0.14 180)',
    description: 'Voice commands, TTS, speech recognition, UX adaptation, accessibility, multi-language.',
    descriptionHe: 'פקודות קוליות, TTS, זיהוי דיבור, התאמת UX, נגישות, רב-שפתי.',
    crates: [
      { name: 'gane-voice', description: 'Voice interaction engine', tests: 28, status: 'active' },
      { name: 'gane-voice-assist', description: 'Voice assistant integration', tests: 22, status: 'active' },
      { name: 'gane-voice-cmd', description: 'Voice command processing', tests: 20, status: 'active' },
      { name: 'gane-voice-ctrl2', description: 'Voice control v2', tests: 18, status: 'active' },
      { name: 'gane-ux', description: 'UX adaptation engine', tests: 32, status: 'active' },
      { name: 'gane-a11y', description: 'Accessibility framework', tests: 25, status: 'active' },
      { name: 'gane-i18n', description: 'Internationalization (43+ languages)', tests: 20, status: 'active' },
      { name: 'gane-nightmode', description: 'Night mode and dark theme', tests: 12, status: 'active' },
      { name: 'gane-alexa-skill', description: 'Alexa skill integration', tests: 15, status: 'active' },
      { name: 'gane-infotainment', description: 'Infotainment system bridge', tests: 18, status: 'active' },
      { name: 'gane-instruments', description: 'Digital instrument cluster', tests: 22, status: 'active' },
      { name: 'gane-ambient-light', description: 'Ambient lighting control', tests: 10, status: 'active' },
      { name: 'gane-modal', description: 'Modal dialog system', tests: 8, status: 'active' },
    ],
  },
  {
    id: 'analytics',
    name: 'Analytics & Telemetry',
    nameHe: 'אנליטיקה וטלמטריה',
    icon: '📊',
    color: 'oklch(0.82 0.15 192)',
    description: 'Telemetry collection, metrics aggregation, distributed tracing, observability, reporting.',
    descriptionHe: 'איסוף טלמטריה, צבירת מטריקות, מעקב מבוזר, צפייה, דיווח.',
    crates: [
      { name: 'gane-telemetry', description: 'Telemetry collection and export', tests: 35, status: 'active' },
      { name: 'gane-metrics', description: 'Metrics aggregation engine', tests: 30, status: 'active' },
      { name: 'gane-analytics', description: 'Analytics processing pipeline', tests: 28, status: 'active' },
      { name: 'gane-observability', description: 'Observability framework', tests: 25, status: 'active' },
      { name: 'gane-tracing-dist', description: 'Distributed tracing', tests: 22, status: 'active' },
      { name: 'gane-histogram', description: 'Histogram data structures', tests: 15, status: 'active' },
      { name: 'gane-monitoring', description: 'System monitoring dashboard', tests: 20, status: 'active' },
      { name: 'gane-report-gen', description: 'Report generation engine', tests: 18, status: 'active' },
      { name: 'gane-report-pdf', description: 'PDF report export', tests: 12, status: 'active' },
      { name: 'gane-report-csv', description: 'CSV data export', tests: 10, status: 'active' },
      { name: 'gane-lineage', description: 'Data lineage tracking', tests: 14, status: 'active' },
      { name: 'gane-explain', description: 'Query explain and optimization', tests: 16, status: 'active' },
    ],
  },
  {
    id: 'infrastructure',
    name: 'Infrastructure & Runtime',
    nameHe: 'תשתית וזמן ריצה',
    icon: '🏗️',
    color: 'oklch(0.55 0.22 264)',
    description: 'Async runtime, thread pools, memory management, concurrency primitives, scheduling.',
    descriptionHe: 'זמן ריצה אסינכרוני, מאגרי חוטים, ניהול זיכרון, פרימיטיבים של מקביליות.',
    crates: [
      { name: 'gane-rt-async2', description: 'Async runtime engine', tests: 22, status: 'active' },
      { name: 'gane-rt-thread2', description: 'Thread pool management', tests: 18, status: 'active' },
      { name: 'gane-rt-io2', description: 'I/O runtime layer', tests: 15, status: 'active' },
      { name: 'gane-rt-timer2', description: 'Timer and scheduling', tests: 12, status: 'active' },
      { name: 'gane-rt-wasm2', description: 'WebAssembly runtime', tests: 20, status: 'active' },
      { name: 'gane-rt-jit', description: 'JIT compilation engine', tests: 15, status: 'active' },
      { name: 'gane-mem-pool2', description: 'Memory pool allocator', tests: 18, status: 'active' },
      { name: 'gane-mem-arena2', description: 'Arena allocator', tests: 14, status: 'active' },
      { name: 'gane-mem-cache3', description: 'Memory cache layer', tests: 16, status: 'active' },
      { name: 'gane-worksteal', description: 'Work-stealing scheduler', tests: 20, status: 'active' },
      { name: 'gane-pipeline', description: 'Data pipeline framework', tests: 25, status: 'active' },
      { name: 'gane-scheduler', description: 'Task scheduler', tests: 22, status: 'active' },
      { name: 'gane-cache', description: 'Multi-tier caching', tests: 28, status: 'active' },
      { name: 'gane-lru', description: 'LRU cache implementation', tests: 15, status: 'active' },
      { name: 'gane-bounded', description: 'Bounded data structures', tests: 12, status: 'active' },
    ],
  },
  {
    id: 'data-storage',
    name: 'Data & Storage',
    nameHe: 'נתונים ואחסון',
    icon: '💾',
    color: 'oklch(0.72 0.14 120)',
    description: 'Database engines, key-value stores, time-series, graph databases, ETL pipelines.',
    descriptionHe: 'מנועי מסד נתונים, מאגרי מפתח-ערך, סדרות זמן, מסדי גרפים.',
    crates: [
      { name: 'gane-storage', description: 'Storage abstraction layer', tests: 30, status: 'active' },
      { name: 'gane-db-postgres', description: 'PostgreSQL driver', tests: 22, status: 'active' },
      { name: 'gane-db-redis', description: 'Redis client', tests: 18, status: 'active' },
      { name: 'gane-db-sqlite', description: 'SQLite embedded database', tests: 20, status: 'active' },
      { name: 'gane-kv', description: 'Key-value store engine', tests: 25, status: 'active' },
      { name: 'gane-vector-db', description: 'Vector database for ML embeddings', tests: 15, status: 'active' },
      { name: 'gane-graphdb', description: 'Graph database engine', tests: 18, status: 'active' },
      { name: 'gane-wide-column', description: 'Wide-column store', tests: 12, status: 'active' },
      { name: 'gane-columnar', description: 'Columnar storage engine', tests: 14, status: 'active' },
      { name: 'gane-wal', description: 'Write-ahead log', tests: 20, status: 'active' },
      { name: 'gane-btree', description: 'B-tree index implementation', tests: 16, status: 'active' },
      { name: 'gane-etl', description: 'ETL pipeline engine', tests: 22, status: 'active' },
      { name: 'gane-migration', description: 'Database migration tool', tests: 12, status: 'active' },
      { name: 'gane-backup', description: 'Backup and recovery', tests: 18, status: 'active' },
    ],
  },
  {
    id: 'security',
    name: 'Security & Auth',
    nameHe: 'אבטחה ואימות',
    icon: '🔐',
    color: 'oklch(0.65 0.22 25)',
    description: 'Authentication, encryption, compliance, zero-trust, HSM, certificate management.',
    descriptionHe: 'אימות, הצפנה, ציות, אפס-אמון, HSM, ניהול תעודות.',
    crates: [
      { name: 'gane-auth', description: 'Authentication and authorization', tests: 35, status: 'active' },
      { name: 'gane-security', description: 'Security framework', tests: 30, status: 'active' },
      { name: 'gane-compliance', description: 'Regulatory compliance engine', tests: 25, status: 'active' },
      { name: 'gane-crypto-aes', description: 'AES encryption', tests: 18, status: 'active' },
      { name: 'gane-crypto-rsa', description: 'RSA encryption', tests: 15, status: 'active' },
      { name: 'gane-crypto-ecdsa', description: 'ECDSA signatures', tests: 14, status: 'active' },
      { name: 'gane-hsm', description: 'Hardware security module', tests: 12, status: 'active' },
      { name: 'gane-fido2', description: 'FIDO2/WebAuthn authentication', tests: 18, status: 'active' },
      { name: 'gane-waf-engine', description: 'Web application firewall', tests: 20, status: 'active' },
      { name: 'gane-firewall', description: 'Network firewall rules', tests: 15, status: 'active' },
      { name: 'gane-dlp', description: 'Data loss prevention', tests: 12, status: 'active' },
      { name: 'gane-anonymize', description: 'Data anonymization', tests: 14, status: 'active' },
      { name: 'gane-audit', description: 'Security audit logging', tests: 22, status: 'active' },
      { name: 'gane-ratelimit', description: 'Rate limiting engine', tests: 20, status: 'active' },
      { name: 'gane-honeypot', description: 'Honeypot intrusion detection', tests: 10, status: 'active' },
    ],
  },
  {
    id: 'networking',
    name: 'Networking & Protocols',
    nameHe: 'רשתות ופרוטוקולים',
    icon: '🌐',
    color: 'oklch(0.72 0.14 180)',
    description: 'TCP/UDP, HTTP/2, gRPC, MQTT, AMQP, mesh networking, protocol buffers.',
    descriptionHe: 'TCP/UDP, HTTP/2, gRPC, MQTT, AMQP, רשת mesh, protocol buffers.',
    crates: [
      { name: 'gane-mesh', description: 'Mesh networking layer', tests: 25, status: 'active' },
      { name: 'gane-net-tcp', description: 'TCP networking', tests: 18, status: 'active' },
      { name: 'gane-net-udp', description: 'UDP networking', tests: 15, status: 'active' },
      { name: 'gane-net-http2', description: 'HTTP/2 client/server', tests: 20, status: 'active' },
      { name: 'gane-net-quic', description: 'QUIC protocol', tests: 18, status: 'active' },
      { name: 'gane-mqtt', description: 'MQTT message broker', tests: 22, status: 'active' },
      { name: 'gane-amqp-client', description: 'AMQP message queue', tests: 15, status: 'active' },
      { name: 'gane-nats', description: 'NATS messaging', tests: 12, status: 'active' },
      { name: 'gane-kafka', description: 'Kafka streaming', tests: 18, status: 'active' },
      { name: 'gane-dns', description: 'DNS resolution', tests: 10, status: 'active' },
      { name: 'gane-cdn', description: 'CDN integration', tests: 14, status: 'active' },
      { name: 'gane-proto-buf', description: 'Protocol buffer codec', tests: 16, status: 'active' },
      { name: 'gane-ftp', description: 'FTP file transfer', tests: 8, status: 'active' },
    ],
  },
  {
    id: 'encoding',
    name: 'Encoding & Compression',
    nameHe: 'קידוד ודחיסה',
    icon: '📦',
    color: 'oklch(0.80 0.16 75)',
    description: 'Data encoding (JSON, Protobuf, Avro, CBOR), compression (zstd, lz4, gzip), archive formats.',
    descriptionHe: 'קידוד נתונים (JSON, Protobuf, Avro), דחיסה (zstd, lz4, gzip), פורמטי ארכיון.',
    crates: [
      { name: 'gane-enc-json4', description: 'JSON encoder/decoder', tests: 18, status: 'active' },
      { name: 'gane-enc-msgpack2', description: 'MessagePack codec', tests: 14, status: 'active' },
      { name: 'gane-enc-cbor2', description: 'CBOR codec', tests: 12, status: 'active' },
      { name: 'gane-enc-protobuf3', description: 'Protobuf codec', tests: 16, status: 'active' },
      { name: 'gane-enc-avro2', description: 'Avro codec', tests: 12, status: 'active' },
      { name: 'gane-enc-flatbuf2', description: 'FlatBuffers codec', tests: 10, status: 'active' },
      { name: 'gane-comp-gzip2', description: 'Gzip compression', tests: 12, status: 'active' },
      { name: 'gane-comp-zstd2', description: 'Zstandard compression', tests: 14, status: 'active' },
      { name: 'gane-comp-lz4v2', description: 'LZ4 compression', tests: 12, status: 'active' },
      { name: 'gane-comp-brotli2', description: 'Brotli compression', tests: 10, status: 'active' },
      { name: 'gane-archive-tar2', description: 'TAR archive format', tests: 8, status: 'active' },
      { name: 'gane-archive-zip2', description: 'ZIP archive format', tests: 10, status: 'active' },
    ],
  },
  {
    id: 'concurrency',
    name: 'Concurrency & Sync',
    nameHe: 'מקביליות וסנכרון',
    icon: '⚙️',
    color: 'oklch(0.55 0.22 264)',
    description: 'Synchronization primitives, channels, atomic operations, lock-free data structures.',
    descriptionHe: 'פרימיטיבים של סנכרון, ערוצים, פעולות אטומיות, מבני נתונים ללא נעילה.',
    crates: [
      { name: 'gane-sync-mutex2', description: 'Mutex implementation', tests: 15, status: 'active' },
      { name: 'gane-sync-rwlock2', description: 'Read-write lock', tests: 14, status: 'active' },
      { name: 'gane-sync-semaphore3', description: 'Semaphore', tests: 12, status: 'active' },
      { name: 'gane-sync-barrier2', description: 'Barrier synchronization', tests: 10, status: 'active' },
      { name: 'gane-sync-atomic2', description: 'Atomic operations', tests: 18, status: 'active' },
      { name: 'gane-sync-spinlock2', description: 'Spinlock', tests: 12, status: 'active' },
      { name: 'gane-sync-mpsc2', description: 'Multi-producer single-consumer', tests: 16, status: 'active' },
      { name: 'gane-sync-mpmc2', description: 'Multi-producer multi-consumer', tests: 14, status: 'active' },
      { name: 'gane-sync-broadcast3', description: 'Broadcast channel', tests: 12, status: 'active' },
      { name: 'gane-sync-watch2', description: 'Watch channel', tests: 10, status: 'active' },
      { name: 'gane-sync-oneshot2', description: 'Oneshot channel', tests: 8, status: 'active' },
      { name: 'gane-crdt', description: 'Conflict-free replicated data types', tests: 20, status: 'active' },
      { name: 'gane-consensus', description: 'Consensus algorithm (Raft)', tests: 22, status: 'active' },
    ],
  },
  {
    id: 'scheduling',
    name: 'Scheduling & Workflow',
    nameHe: 'תזמון ותהליכי עבודה',
    icon: '📋',
    color: 'oklch(0.72 0.14 120)',
    description: 'Task scheduling (FIFO, priority, cron), workflow engines, batch processing.',
    descriptionHe: 'תזמון משימות (FIFO, עדיפות, cron), מנועי תהליכי עבודה, עיבוד אצווה.',
    crates: [
      { name: 'gane-sched-fifo2', description: 'FIFO scheduler', tests: 12, status: 'active' },
      { name: 'gane-sched-priority3', description: 'Priority scheduler', tests: 14, status: 'active' },
      { name: 'gane-sched-round2', description: 'Round-robin scheduler', tests: 10, status: 'active' },
      { name: 'gane-sched-cron2', description: 'Cron scheduler', tests: 16, status: 'active' },
      { name: 'gane-sched-batch3', description: 'Batch job scheduler', tests: 14, status: 'active' },
      { name: 'gane-sched-deadline2', description: 'Deadline scheduler', tests: 12, status: 'active' },
      { name: 'gane-wf-engine2', description: 'Workflow engine', tests: 20, status: 'active' },
      { name: 'gane-wf-state2', description: 'Workflow state machine', tests: 15, status: 'active' },
      { name: 'gane-wf-parallel', description: 'Parallel workflow execution', tests: 12, status: 'active' },
      { name: 'gane-wf-template', description: 'Workflow templates', tests: 10, status: 'active' },
      { name: 'gane-wf-audit2', description: 'Workflow audit trail', tests: 14, status: 'active' },
      { name: 'gane-dag', description: 'Directed acyclic graph engine', tests: 18, status: 'active' },
    ],
  },
  {
    id: 'testing-devops',
    name: 'Testing & DevOps',
    nameHe: 'בדיקות ו-DevOps',
    icon: '🧪',
    color: 'oklch(0.75 0.18 150)',
    description: 'Test framework, CI/CD, Docker, Kubernetes, deployment, benchmarking.',
    descriptionHe: 'מסגרת בדיקות, CI/CD, Docker, Kubernetes, פריסה, מדידת ביצועים.',
    crates: [
      { name: 'gane-test-framework', description: 'Test framework and utilities', tests: 30, status: 'active' },
      { name: 'gane-integration-tests', description: 'Integration test suite', tests: 45, status: 'active' },
      { name: 'gane-e2e-tests', description: 'End-to-end test suite', tests: 35, status: 'active' },
      { name: 'gane-bench', description: 'Benchmarking framework', tests: 20, status: 'active' },
      { name: 'gane-deploy', description: 'Deployment automation', tests: 18, status: 'active' },
      { name: 'gane-k8s', description: 'Kubernetes orchestration', tests: 15, status: 'active' },
      { name: 'gane-helm', description: 'Helm chart management', tests: 12, status: 'active' },
      { name: 'gane-ci', description: 'CI pipeline configuration', tests: 10, status: 'active' },
      { name: 'gane-gitops', description: 'GitOps workflow', tests: 14, status: 'active' },
      { name: 'gane-ansible', description: 'Ansible automation', tests: 12, status: 'active' },
      { name: 'gane-canary', description: 'Canary deployment', tests: 16, status: 'active' },
      { name: 'gane-rollout', description: 'Rolling deployment', tests: 14, status: 'active' },
      { name: 'gane-docs', description: 'Documentation generator', tests: 10, status: 'active' },
      { name: 'gane-perf', description: 'Performance profiling', tests: 18, status: 'active' },
    ],
  },
];

// Helper: count total crates across all layers
export function getTotalDisplayedCrates(): number {
  return systemLayers.reduce((sum, layer) => sum + layer.crates.length, 0);
}

// Helper: count total tests across all layers
export function getTotalDisplayedTests(): number {
  return systemLayers.reduce((sum, layer) =>
    sum + layer.crates.reduce((s, c) => s + c.tests, 0), 0);
}

// Helper: get layer stats with computed totals (used by SystemArchPanel)
export function getLayerStats() {
  return systemLayers.map(layer => ({
    ...layer,
    totalCrates: layer.crates.length,
    totalTests: layer.crates.reduce((s, c) => s + c.tests, 0),
    activeCount: layer.crates.filter(c => c.status === 'active').length,
    buildingCount: layer.crates.filter(c => c.status === 'building').length,
    plannedCount: layer.crates.filter(c => c.status === 'planned').length,
  }));
}
