//! Vitals monitoring — tracks physiological signals for driver health assessment.

use std::collections::VecDeque;
use std::time::Instant;

/// Heart rate zone classification.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HeartRateZone {
    /// Below normal resting rate — possible bradycardia or deep relaxation.
    Low,
    /// Normal resting range.
    Normal,
    /// Elevated — mild stress or physical activity.
    Elevated,
    /// High — significant stress, anxiety, or medical concern.
    High,
    /// Critical — potential medical emergency.
    Critical,
}

/// A single vital signs reading.
#[derive(Debug, Clone)]
pub struct VitalReading {
    /// Heart rate (beats per minute), if available.
    pub heart_rate_bpm: Option<f64>,
    /// Heart rate variability (ms), if available.
    pub hrv_ms: Option<f64>,
    /// Skin conductance (μS), if available — high values indicate stress.
    pub skin_conductance: Option<f64>,
    /// Skin temperature (°C), if available.
    pub skin_temperature: Option<f64>,
    /// Blood oxygen saturation (%), if available.
    pub spo2: Option<f64>,
    /// Timestamp of the reading.
    pub timestamp: Instant,
}

/// Configuration for vitals monitoring.
#[derive(Debug, Clone)]
pub struct VitalsConfig {
    /// Normal resting heart rate range.
    pub normal_hr_min: f64,
    pub normal_hr_max: f64,
    /// Elevated heart rate threshold.
    pub elevated_hr: f64,
    /// High heart rate threshold.
    pub high_hr: f64,
    /// Critical heart rate threshold.
    pub critical_hr: f64,
    /// Normal HRV range (ms).
    pub normal_hrv_min: f64,
    /// Low SpO2 threshold (%).
    pub low_spo2: f64,
    /// Maximum readings to retain.
    pub max_readings: usize,
}

impl Default for VitalsConfig {
    fn default() -> Self {
        Self {
            normal_hr_min: 50.0,
            normal_hr_max: 90.0,
            elevated_hr: 100.0,
            high_hr: 120.0,
            critical_hr: 150.0,
            normal_hrv_min: 20.0,
            low_spo2: 92.0,
            max_readings: 300,
        }
    }
}

/// Health alert generated by vitals monitoring.
#[derive(Debug, Clone)]
pub struct HealthAlert {
    /// Type of alert.
    pub alert_type: HealthAlertType,
    /// Severity (0.0 = informational, 1.0 = emergency).
    pub severity: f64,
    /// Human-readable description.
    pub description: String,
}

/// Type of health alert.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HealthAlertType {
    /// Abnormal heart rate.
    HeartRate,
    /// Low heart rate variability (stress indicator).
    LowHrv,
    /// Low blood oxygen.
    LowOxygen,
    /// High stress detected.
    HighStress,
    /// Possible medical emergency.
    MedicalEmergency,
}

/// Vitals monitoring engine.
pub struct VitalsMonitor {
    config: VitalsConfig,
    readings: VecDeque<VitalReading>,
}

impl VitalsMonitor {
    /// Create a new vitals monitor.
    pub fn new(config: VitalsConfig) -> Self {
        Self {
            config,
            readings: VecDeque::new(),
        }
    }

    /// Create with default configuration.
    pub fn with_defaults() -> Self {
        Self::new(VitalsConfig::default())
    }

    /// Add a vital signs reading and check for alerts.
    pub fn add_reading(&mut self, reading: VitalReading) -> Vec<HealthAlert> {
        let alerts = self.check_alerts(&reading);

        self.readings.push_back(reading);
        if self.readings.len() > self.config.max_readings {
            self.readings.pop_front();
        }

        alerts
    }

    /// Get the number of readings recorded.
    pub fn reading_count(&self) -> usize {
        self.readings.len()
    }

    /// Classify the current heart rate zone.
    pub fn heart_rate_zone(&self, hr: f64) -> HeartRateZone {
        if hr >= self.config.critical_hr {
            HeartRateZone::Critical
        } else if hr >= self.config.high_hr {
            HeartRateZone::High
        } else if hr >= self.config.elevated_hr {
            HeartRateZone::Elevated
        } else if hr >= self.config.normal_hr_min {
            HeartRateZone::Normal
        } else {
            HeartRateZone::Low
        }
    }

    /// Calculate average heart rate from recent readings.
    pub fn average_heart_rate(&self) -> Option<f64> {
        let hrs: Vec<f64> = self
            .readings
            .iter()
            .filter_map(|r| r.heart_rate_bpm)
            .collect();
        if hrs.is_empty() {
            None
        } else {
            Some(hrs.iter().sum::<f64>() / hrs.len() as f64)
        }
    }

    /// Calculate stress level from recent readings (0.0 = calm, 1.0 = very stressed).
    pub fn stress_level(&self) -> f64 {
        if self.readings.is_empty() {
            return 0.0;
        }

        let mut stress_factors = Vec::new();

        // Heart rate factor
        if let Some(avg_hr) = self.average_heart_rate() {
            let hr_stress = if avg_hr > self.config.normal_hr_max {
                ((avg_hr - self.config.normal_hr_max) / 60.0).clamp(0.0, 1.0)
            } else {
                0.0
            };
            stress_factors.push(hr_stress);
        }

        // HRV factor (low HRV = high stress)
        let hrvs: Vec<f64> = self.readings.iter().filter_map(|r| r.hrv_ms).collect();
        if !hrvs.is_empty() {
            let avg_hrv = hrvs.iter().sum::<f64>() / hrvs.len() as f64;
            let hrv_stress = if avg_hrv < self.config.normal_hrv_min {
                1.0 - (avg_hrv / self.config.normal_hrv_min)
            } else {
                0.0
            };
            stress_factors.push(hrv_stress);
        }

        // Skin conductance factor
        let scs: Vec<f64> = self
            .readings
            .iter()
            .filter_map(|r| r.skin_conductance)
            .collect();
        if !scs.is_empty() {
            let avg_sc = scs.iter().sum::<f64>() / scs.len() as f64;
            // Normal skin conductance is ~2-5 μS, stressed is >10 μS
            let sc_stress = ((avg_sc - 5.0) / 15.0).clamp(0.0, 1.0);
            stress_factors.push(sc_stress);
        }

        if stress_factors.is_empty() {
            0.0
        } else {
            stress_factors.iter().sum::<f64>() / stress_factors.len() as f64
        }
    }

    fn check_alerts(&self, reading: &VitalReading) -> Vec<HealthAlert> {
        let mut alerts = Vec::new();

        // Heart rate alerts
        if let Some(hr) = reading.heart_rate_bpm {
            match self.heart_rate_zone(hr) {
                HeartRateZone::Critical => {
                    alerts.push(HealthAlert {
                        alert_type: HealthAlertType::MedicalEmergency,
                        severity: 1.0,
                        description: format!("Critical heart rate: {hr:.0} bpm"),
                    });
                }
                HeartRateZone::High => {
                    alerts.push(HealthAlert {
                        alert_type: HealthAlertType::HeartRate,
                        severity: 0.7,
                        description: format!("High heart rate: {hr:.0} bpm"),
                    });
                }
                HeartRateZone::Low if hr < 40.0 => {
                    alerts.push(HealthAlert {
                        alert_type: HealthAlertType::MedicalEmergency,
                        severity: 0.9,
                        description: format!("Dangerously low heart rate: {hr:.0} bpm"),
                    });
                }
                _ => {}
            }
        }

        // Low HRV alert
        if let Some(hrv) = reading.hrv_ms {
            if hrv < self.config.normal_hrv_min * 0.5 {
                alerts.push(HealthAlert {
                    alert_type: HealthAlertType::LowHrv,
                    severity: 0.5,
                    description: format!("Very low HRV: {hrv:.0} ms — high stress"),
                });
            }
        }

        // Low SpO2 alert
        if let Some(spo2) = reading.spo2 {
            if spo2 < self.config.low_spo2 {
                let severity = if spo2 < 88.0 { 1.0 } else { 0.6 };
                alerts.push(HealthAlert {
                    alert_type: HealthAlertType::LowOxygen,
                    severity,
                    description: format!("Low blood oxygen: {spo2:.0}%"),
                });
            }
        }

        alerts
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn normal_reading() -> VitalReading {
        VitalReading {
            heart_rate_bpm: Some(72.0),
            hrv_ms: Some(45.0),
            skin_conductance: Some(3.0),
            skin_temperature: Some(33.5),
            spo2: Some(98.0),
            timestamp: Instant::now(),
        }
    }

    #[test]
    fn test_normal_reading_no_alerts() {
        let mut monitor = VitalsMonitor::with_defaults();
        let alerts = monitor.add_reading(normal_reading());
        assert!(alerts.is_empty(), "Normal reading should produce no alerts");
    }

    #[test]
    fn test_critical_heart_rate_alert() {
        let mut monitor = VitalsMonitor::with_defaults();
        let reading = VitalReading {
            heart_rate_bpm: Some(160.0),
            ..normal_reading()
        };
        let alerts = monitor.add_reading(reading);
        assert_eq!(alerts.len(), 1);
        assert_eq!(alerts[0].alert_type, HealthAlertType::MedicalEmergency);
        assert_eq!(alerts[0].severity, 1.0);
    }

    #[test]
    fn test_high_heart_rate_alert() {
        let mut monitor = VitalsMonitor::with_defaults();
        let reading = VitalReading {
            heart_rate_bpm: Some(130.0),
            ..normal_reading()
        };
        let alerts = monitor.add_reading(reading);
        assert_eq!(alerts.len(), 1);
        assert_eq!(alerts[0].alert_type, HealthAlertType::HeartRate);
    }

    #[test]
    fn test_very_low_heart_rate_emergency() {
        let mut monitor = VitalsMonitor::with_defaults();
        let reading = VitalReading {
            heart_rate_bpm: Some(35.0),
            ..normal_reading()
        };
        let alerts = monitor.add_reading(reading);
        assert!(alerts
            .iter()
            .any(|a| a.alert_type == HealthAlertType::MedicalEmergency));
    }

    #[test]
    fn test_low_spo2_alert() {
        let mut monitor = VitalsMonitor::with_defaults();
        let reading = VitalReading {
            spo2: Some(90.0),
            ..normal_reading()
        };
        let alerts = monitor.add_reading(reading);
        assert!(alerts
            .iter()
            .any(|a| a.alert_type == HealthAlertType::LowOxygen));
    }

    #[test]
    fn test_low_hrv_alert() {
        let mut monitor = VitalsMonitor::with_defaults();
        let reading = VitalReading {
            hrv_ms: Some(8.0), // Very low — below 50% of threshold (10)
            ..normal_reading()
        };
        let alerts = monitor.add_reading(reading);
        assert!(alerts
            .iter()
            .any(|a| a.alert_type == HealthAlertType::LowHrv));
    }

    #[test]
    fn test_heart_rate_zone_classification() {
        let monitor = VitalsMonitor::with_defaults();
        assert_eq!(monitor.heart_rate_zone(40.0), HeartRateZone::Low);
        assert_eq!(monitor.heart_rate_zone(72.0), HeartRateZone::Normal);
        assert_eq!(monitor.heart_rate_zone(105.0), HeartRateZone::Elevated);
        assert_eq!(monitor.heart_rate_zone(130.0), HeartRateZone::High);
        assert_eq!(monitor.heart_rate_zone(160.0), HeartRateZone::Critical);
    }

    #[test]
    fn test_average_heart_rate() {
        let mut monitor = VitalsMonitor::with_defaults();
        monitor.add_reading(VitalReading {
            heart_rate_bpm: Some(70.0),
            ..normal_reading()
        });
        monitor.add_reading(VitalReading {
            heart_rate_bpm: Some(80.0),
            ..normal_reading()
        });
        let avg = monitor.average_heart_rate().unwrap();
        assert!((avg - 75.0).abs() < 0.01);
    }

    #[test]
    fn test_stress_level_calm() {
        let mut monitor = VitalsMonitor::with_defaults();
        for _ in 0..5 {
            monitor.add_reading(normal_reading());
        }
        let stress = monitor.stress_level();
        assert!(
            stress < 0.3,
            "Normal vitals should produce low stress, got {stress}"
        );
    }

    #[test]
    fn test_stress_level_high() {
        let mut monitor = VitalsMonitor::with_defaults();
        for _ in 0..5 {
            monitor.add_reading(VitalReading {
                heart_rate_bpm: Some(110.0),
                hrv_ms: Some(10.0),           // Very low HRV
                skin_conductance: Some(15.0), // High skin conductance
                ..normal_reading()
            });
        }
        let stress = monitor.stress_level();
        assert!(
            stress > 0.4,
            "Stressed vitals should produce high stress, got {stress}"
        );
    }

    #[test]
    fn test_reading_count() {
        let mut monitor = VitalsMonitor::with_defaults();
        for _ in 0..10 {
            monitor.add_reading(normal_reading());
        }
        assert_eq!(monitor.reading_count(), 10);
    }

    #[test]
    fn test_max_readings_enforced() {
        let config = VitalsConfig {
            max_readings: 5,
            ..Default::default()
        };
        let mut monitor = VitalsMonitor::new(config);
        for _ in 0..20 {
            monitor.add_reading(normal_reading());
        }
        assert_eq!(monitor.reading_count(), 5);
    }

    #[test]
    fn test_multiple_alerts_simultaneously() {
        let mut monitor = VitalsMonitor::with_defaults();
        let reading = VitalReading {
            heart_rate_bpm: Some(160.0), // Critical HR
            hrv_ms: Some(5.0),           // Very low HRV
            spo2: Some(85.0),            // Low SpO2
            ..normal_reading()
        };
        let alerts = monitor.add_reading(reading);
        assert!(
            alerts.len() >= 3,
            "Should produce multiple alerts, got {}",
            alerts.len()
        );
    }
}
